"""add passive deletes all and ondelete cascade

Revision ID: 6e2b6b67aedc
Revises: 16e01f1a960b
Create Date: 2026-01-27 22:24:12.591649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6e2b6b67aedc'
down_revision: Union[str, Sequence[str], None] = '16e01f1a960b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('items_user_id_fkey'), 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(op.f('items_user_id_fkey'), 'items', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
