"""switch users to sqlmodel

Revision ID: e3d80ff69199
Revises: 4f05e5020e85
Create Date: 2025-12-23 11:59:17.313376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e3d80ff69199'
down_revision: Union[str, Sequence[str], None] = '4f05e5020e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # удаляем таблицу users с потерей данных
    op.drop_table('users')

    # создаем таблицу users заново
    op.create_table(
        'users',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('username', sa.String(length=64), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
    )
    # оставляем создание индекса без изменений
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # откат назад тоже через пересоздание таблицы с потерей данных
    op.drop_table('users')

    # создаем таблицу users заново
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
