"""add ondelete restrict

Revision ID: 16e01f1a960b
Revises: e2327aa980bc
Create Date: 2026-01-27 21:47:27.508957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '16e01f1a960b'
down_revision: Union[str, Sequence[str], None] = 'e2327aa980bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('items_user_id_fkey'), 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(op.f('items_user_id_fkey'), 'items', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('items', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
